convert to new header layout add doc build mechanism add doc install rules NOW: 'make all;sudo make install'        # this builds & installs brickOS NOW: 'make docs;sudo make docs-install'  # this generates & installs docs

diff --git a/doc/Makefile b/doc/Makefile
--- a/doc/Makefile
+++ b/doc/Makefile
@@ -1,15 +1,23 @@
 ### ==========================================================================
-###  $Id: Makefile,v 1.4 2002/10/11 09:13:04 stephmo Exp $
-###  FILE: doc/Makefile - doc (sgml -> html) rules
+###  $Id: Makefile,v 1.5 2002/10/15 07:02:07 stephmo Exp $
+###  FILE: doc/Makefile - build HTML documentation from SGML source
+###  brickOS - the independent LEGO Mindstorms OS
 ### --------------------------------------------------------------------------
-###  Experimenal make rules for building HTML documentation from SGML source
-###   by Stephen M Moraco
-###
+
 DOCBASE = INSTALL-cygwin
 DOCSRC = $(DOCBASE).sgml
 
 DOCBASE2 = HOWTO
 DOCSRC2 = $(DOCBASE2).sgml
+
+TEXT_DOCS = AvailableDocs.txt \
+            Notes_on_intterupts \
+            Pros_and_Cons \
+            RCXmessageAPI.txt \
+            Sensors
+
+
+include ../Makefile.common
 
 #  out default target when doing make in this directory
 doc: $(DOCBASE).html $(DOCBASE2).html
@@ -18,8 +26,30 @@ doc: $(DOCBASE).html $(DOCBASE2).html
 all install depend:
 	@# nothing to do here, but do this nothing silently
 
+docs-install: ${pkghtmldir} chkbuild
+	-@cp -f ../[CLNRV]* ${pkgdocdir} 2>/dev/null
+	cp -f ${TEXT_DOCS} ${pkgdocdir} 
+	cp -r images ${pkghtmldir}
+	cp -f *.html ${pkghtmldir}
+	cp HOWTO/*.html ${pkghtmldir}
+	@# oops copied extra file, remove it
+	@rm -f $(pkghtmldir)/t1.html
+
+chkbuild:
+	@if [ ! -f $(DOCBASE).html -o ! -f $(DOCBASE2).html ] ;then \
+		echo ""; \
+		echo "---------------------------------------------------------"; \
+		echo "  Documents are not built. Please run 'make doc' then "; \
+		echo "    rerun 'make doc-install' as root"; \
+		echo "---------------------------------------------------------"; \
+		echo ""; \
+		exit 2; \
+	fi
+
+${pkghtmldir}:
+	mkdir -p $@
+
 $(DOCBASE).html: $(DOCSRC)
-	mkdir -p $(DOCBASE)/images
 	sgmltools -b html $(DOCBASE)
 	#  correct for incorrect image path
 	sed -e 's/\/docbook-dsssl/images/' $(DOCBASE)/top.html >$@
@@ -29,7 +59,6 @@ realclean::
 	rm -f $(DOCBASE).html
 
 $(DOCBASE2).html: $(DOCSRC2)
-	mkdir -p $(DOCBASE2)/images
 	sgmltools -b html $(DOCBASE2)
 	#  correct for incorrect image path
 	sed -e 's/\/docbook-dsssl/images/' $(DOCBASE2)/t1.html >$@
@@ -37,6 +66,9 @@ $(DOCBASE2).html: $(DOCSRC2)
 realclean::
 	rm -f $(DOCBASE2).html
 	rm -rf $(DOCBASE2)
+
+tag:
+	@# nothing to do here but do it silently
 
 clean:
 	@# nothing to do here, but do this nothing silently
@@ -46,5 +78,5 @@ clean:
 realclean:: clean
 
 ### --------------------------------------------------------------------------
-###    End of file: doc/Makefile
+###                            End of FILE: doc/Makefile
 ### ==========================================================================
